// MOVE THIS FILE TO wifiopts.h

#ifndef _WIFIOPTS_H
#define _WIFIOPTS_H
#include "lwipopts.h"

#define IP_PRIMARY "192.168.\0"

#define SSID "INSERT PRIMARY NETWORK SSID"
#define PASS "INSERT PRIMARY NEWROWK PASSWORD"
#define SSID2 "[OPTIONAL: INSERT FAILOVER NETWORK SSID]"
#define PASS2 "[OPTIONAL: INSERT FAILOVER NETWORK PASSWORD]"
#define SEND_BUF 16383 //16KiB-1

#endif